/**
 * Test fixtures — sample data for unit tests.
 */

export const sampleTransactions = [
	{
		id: 1,
		plaid_transaction_id: "tx_001",
		name: "Uber Eats",
		amount: 25.5,
		effective_amount: 25.5,
		date: "2026-04-01",
		category: "FOOD_AND_DRINK",
		subcategory: "RESTAURANTS",
		card_name: "Amex Platinum",
		mask: "1234",
		account_id: 100,
		is_splitwise: false,
		is_deleted: false,
		is_edited: false,
		splits: null,
		total_credits: 0,
		credits: null,
		pending: false,
		logo_url: null,
		is_authorized_user_transaction: false,
	},
	{
		id: 2,
		plaid_transaction_id: "tx_002",
		name: "Netflix",
		amount: 15.99,
		effective_amount: 15.99,
		date: "2026-04-02",
		category: "ENTERTAINMENT",
		subcategory: "STREAMING",
		card_name: "Chase Sapphire",
		mask: "5678",
		account_id: 101,
		is_splitwise: false,
		is_deleted: false,
		is_edited: false,
		splits: null,
		total_credits: 0,
		credits: null,
		pending: false,
		logo_url: null,
		is_authorized_user_transaction: false,
	},
];

export const sampleAccounts = [
	{
		id: 100,
		name: "Amex Platinum Card",
		mask: "1234",
		type: "credit",
		subtype: "credit card",
		current_balance: 1500.0,
		available_balance: 8500.0,
		iso_currency_code: "USD",
		plaid_institution_id: "ins_1",
		item_id: 1,
		is_splitwise: false,
	},
	{
		id: 101,
		name: "Chase Sapphire Reserve",
		mask: "5678",
		type: "credit",
		subtype: "credit card",
		current_balance: 500.0,
		available_balance: 9500.0,
		iso_currency_code: "USD",
		plaid_institution_id: "ins_2",
		item_id: 2,
		is_splitwise: false,
	},
];

export const sampleBenefitConfigs = [
	{
		id: "config-001",
		benefit_name: "Uber Cash",
		benefit_key: "uber_cash",
		description: "$15/month in Uber Cash",
		frequency: "monthly",
		amount: "15.00",
		card_id: "card-001",
		merchant_patterns: ["UBER", "UBER EATS"],
		trackable: true,
		untrackable_reason: null,
		effective_from: "2026-01-01",
		effective_until: null,
	},
	{
		id: "config-002",
		benefit_name: "Digital Entertainment",
		benefit_key: "digital_entertainment",
		description: "$20/month for streaming",
		frequency: "monthly",
		amount: "20.00",
		card_id: "card-001",
		merchant_patterns: ["NETFLIX", "HULU", "DISNEY"],
		trackable: true,
		untrackable_reason: null,
		effective_from: "2026-01-01",
		effective_until: null,
	},
];
